# Generated by Django 4.0 on 2021-12-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('chess_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='made_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='main.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='bets',
            field=models.ManyToManyField(to='chess_backend.Bet'),
        ),
        migrations.AddField(
            model_name='game',
            name='black',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='black_player', to='main.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.ManyToManyField(to='chess_backend.Move'),
        ),
        migrations.AddField(
            model_name='game',
            name='white',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white_player', to='main.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_player', to='main.user'),
        ),
        migrations.AddField(
            model_name='bet',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_winner', to='main.user'),
        ),
    ]
